// ⚡ Auto-generated by generateRoutes.ts — DO NOT EDIT MANUALLY
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Qrcode from "./pages/wajs/qrcode";
import WebhookCreate from "./pages/sq/dashboard/webhook/webhook_create";
import WebhookEdit from "./pages/sq/dashboard/webhook/webhook_edit";
import WebhookHome from "./pages/sq/dashboard/webhook/webhook_home";
import WebhookLayout from "./pages/sq/dashboard/webhook/webhook_layout";
import WajsHome from "./pages/sq/dashboard/wajs/wajs_home";
import WajsLayout from "./pages/sq/dashboard/wajs/wajs_layout";
import ApikeyPage from "./pages/sq/dashboard/apikey/apikey_page";
import DashboardPage from "./pages/sq/dashboard/dashboard_page";
import DashboardLayout from "./pages/sq/dashboard/dashboard_layout";
import SqLayout from "./pages/sq/sq_layout";
import Login from "./pages/Login";
import Home from "./pages/Home";
import NotFound from "./pages/NotFound";

export default function AppRoutes() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/wajs/qrcode" element={<Qrcode />} />

        <Route path="/sq" element={<SqLayout />}>
          <Route path="/sq/dashboard" element={<DashboardLayout />}>
            <Route path="/sq/dashboard/webhook" element={<WebhookLayout />}>
              <Route index element={<WebhookHome />} />

              <Route
                path="/sq/dashboard/webhook/webhook-create"
                element={<WebhookCreate />}
              />
              <Route
                path="/sq/dashboard/webhook/webhook-edit"
                element={<WebhookEdit />}
              />
              <Route
                path="/sq/dashboard/webhook/webhook-home"
                element={<WebhookHome />}
              />
            </Route>

            <Route path="/sq/dashboard/wajs" element={<WajsLayout />}>
              <Route index element={<WajsHome />} />

              <Route
                path="/sq/dashboard/wajs/wajs-home"
                element={<WajsHome />}
              />
            </Route>
            <Route
              path="/sq/dashboard/apikey/apikey"
              element={<ApikeyPage />}
            />
            <Route path="/sq/dashboard/dashboard" element={<DashboardPage />} />
          </Route>
        </Route>
        <Route path="/login" element={<Login />} />
        <Route path="/" element={<Home />} />
        <Route path="/*" element={<NotFound />} />
      </Routes>
    </BrowserRouter>
  );
}
